apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - python manage.py migrate --noinput && gunicorn notesapp.wsgi --bind 0.0.0.0:8000
          envFrom:
            - configMapRef:
                name: notes-config
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notes-app
  ports:
    - port: 80
      targetPort: 8000
